import type { Metadata } from 'next';
import { Inter, Kanit } from 'next/font/google';
import './globals.css';
import './main.scss';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import { Analytics } from '@vercel/analytics/react';

const inter = Inter({ subsets: ['latin'] });
const kanit = Kanit({ subsets: ['latin'], weight: '400' });

// export const metadata: Metadata = {
//   title: 'Tan Freight | Home',
//   description: 'Generated by create next app',
// };
export const metadata: Metadata = {
  title: {
    template: '%s | TAN Freight',
    default: 'Home | TAN Freight and Logistics',
  },
  description:
    'Reimagining the face of Freight and Logistics services. Your reliable and genuine partner for all your freight and logistics needs, ensuring smooth and efficient transportation solutions tailored to your requirements. Trust us for dependable and authentic services that prioritize your business success Air Freight | Sea Freight | Land Freight |Ship to Ghana | Shop online | buy from china | Customs Clearance | Warehousing | Project cargo | Consolidation | Ship goods | ship conatainer | From china to Ghana | from USA to Ghana | shipping',
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <Navigation />
        <main className="relative overflow-hidden">{children}</main>
        <Analytics />
        <Footer />
      </body>
    </html>
  );
}
