import SDG from '@/components/SDG';
import { Metadata } from 'next';
import Image from 'next/image';
import React from 'react';
export const metadata: Metadata = {
  title: 'TAN SDG',
  description: 'Generated by create next app',
};
const page = () => {
  return (
    <section className="mx-2 lg:mx-4">
      <div className="relative mx-2 mb-8">
        <Image
          src="/tanlogo.png"
          alt="tan logo"
          width={50}
          height={50}
          className="absolute left-[-5px] top-[-28px] w-10 lg:w-[50px]"
        />
        <h2 className="text-xl font-bold lg:text-3xl">
          TAN SUSTAINABLE DEVELOPMENT GOALS
        </h2>
        <p className="regular-14 lg:regular-16 text-gray-30 lg:w-3/5">
          TAN contribution to Sustainable Development Goals aim to address some
          of the global challenges by promoting sustainable development,
          reducing inequalities, and improving the well-being of all
          individuals.
        </p>
      </div>
      <SDG />
    </section>
  );
};

export default page;
